### ISSUE TITLE
attempts to import a module with the same schema id should generate an informative error

### ISSUE THREAD

**Issue by cmungall** [biolink/linkml#105]
Given

```yaml
id: https://w3id.org/my_schema
name: my_schema
description: >-
  My Schema Description
imports:
 - biolinkml:types
 - my_core
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  my_schema: https://w3id.org/mixs/my_schema/
default_prefix: my_schema

slots:
  name:
    description: >-
      example slot

classes:
  my class:
    is_a: named thing
    slots:
      - name
```

and `my_core.yaml`:

```yaml
id: https://w3id.org/my_schema
name: my_core
description: >-
  This is an example of an imported module
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  my_core: https://w3id.org/mixs/my_core/
default_prefix: my_core

slots:
  id:
    identifier: true
    required: true
classes:
  named thing:
    description: >-
      root class
    slots:
      - id
```

note the imported module has the same id as the importer - an unintentional error on the part of the user

running any of the generators yields the same error:

```bash
ValueError: File "/Users/cjm/repos/linkml-template/src/schema/my_schema.linkml.yaml", line 20, col 11:  Class: "my class" - unknown is_a reference: named thing
```

this is confusing, as my_class is clearly defined in the importer. I assume the actual issue is caused by the clashing id. It would be more informative to generate an error up-front
